import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean, json } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Social media accounts configuration table
 * Stores API credentials and settings for different social media platforms
 */
export const socialMediaAccounts = mysqlTable("social_media_accounts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  platform: mysqlEnum("platform", ["linkedin", "facebook", "twitter", "instagram"]).notNull(),
  accountName: varchar("accountName", { length: 255 }).notNull(),
  accessToken: text("accessToken").notNull(),
  refreshToken: text("refreshToken"),
  accountId: varchar("accountId", { length: 255 }).notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type SocialMediaAccount = typeof socialMediaAccounts.$inferSelect;
export type InsertSocialMediaAccount = typeof socialMediaAccounts.$inferInsert;

/**
 * AI-generated social media posts
 * Stores content generated by the AI agent for each platform
 */
export const generatedPosts = mysqlTable("generated_posts", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  platform: mysqlEnum("platform", ["linkedin", "facebook", "twitter", "instagram"]).notNull(),
  title: varchar("title", { length: 255 }),
  content: text("content").notNull(),
  imageUrl: text("imageUrl"),
  hashtags: text("hashtags"),
  status: mysqlEnum("status", ["draft", "scheduled", "published", "failed"]).default("draft").notNull(),
  scheduledAt: timestamp("scheduledAt"),
  publishedAt: timestamp("publishedAt"),
  engagement: json("engagement"),
  externalPostId: varchar("externalPostId", { length: 255 }),
  errorMessage: text("errorMessage"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type GeneratedPost = typeof generatedPosts.$inferSelect;
export type InsertGeneratedPost = typeof generatedPosts.$inferInsert;

/**
 * AI Agent configuration and scheduling
 * Stores settings for the daily posting agent
 */
export const aiAgentConfig = mysqlTable("ai_agent_config", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  agentName: varchar("agentName", { length: 255 }).notNull().default("BinaryKode Daily Poster"),
  isActive: boolean("isActive").default(true).notNull(),
  postingSchedule: json("postingSchedule").notNull(),
  platforms: json("platforms").notNull(),
  contentStyle: text("contentStyle"),
  agencyInfo: json("agencyInfo").notNull(),
  maxPostsPerDay: int("maxPostsPerDay").default(1).notNull(),
  includeImages: boolean("includeImages").default(true).notNull(),
  includeHashtags: boolean("includeHashtags").default(true).notNull(),
  lastRunAt: timestamp("lastRunAt"),
  nextRunAt: timestamp("nextRunAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AIAgentConfig = typeof aiAgentConfig.$inferSelect;
export type InsertAIAgentConfig = typeof aiAgentConfig.$inferInsert;

/**
 * Posting history and logs
 * Tracks all posting attempts and results for monitoring
 */
export const postingLogs = mysqlTable("posting_logs", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  agentConfigId: int("agentConfigId").notNull(),
  generatedPostId: int("generatedPostId"),
  platform: mysqlEnum("platform", ["linkedin", "facebook", "twitter", "instagram"]).notNull(),
  status: mysqlEnum("status", ["success", "failed", "pending"]).notNull(),
  message: text("message"),
  errorDetails: text("errorDetails"),
  attemptedAt: timestamp("attemptedAt").defaultNow().notNull(),
  completedAt: timestamp("completedAt"),
});

export type PostingLog = typeof postingLogs.$inferSelect;
export type InsertPostingLog = typeof postingLogs.$inferInsert;

/**
 * Content templates for AI generation
 * Stores predefined templates that the AI can use to generate varied content
 */
export const contentTemplates = mysqlTable("content_templates", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  template: text("template").notNull(),
  platform: mysqlEnum("platform", ["linkedin", "facebook", "twitter", "instagram"]).notNull(),
  category: varchar("category", { length: 100 }),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ContentTemplate = typeof contentTemplates.$inferSelect;
export type InsertContentTemplate = typeof contentTemplates.$inferInsert;